### ISSUE TITLE
Errors.....Help

### ISSUE THREAD

**Issue by rdearm1** [mspnp/ha-nva#42]
Ok. So I had to deploy manually to because the Deploy.ps1 did not work I was able to complete all the setups successfully but now I get the following when I start the client monitor containers.

/nva-docker-entrypoint.sh
su-exec
2017-08-11 16:55:32,184 ERROR [main:Main@80] - Error running daemon
org.apache.commons.daemon.DaemonInitException: Error processing command line arguments
        at com.microsoft.azure.practices.nvadaemon.NvaDaemon.init(NvaDaemon.java:62)
        at com.microsoft.azure.practices.nvadaemon.Main.runDaemon(Main.java:22)
        at com.microsoft.azure.practices.nvadaemon.Main.main(Main.java:78)
2017-08-11 16:55:32,199 INFO  [Thread-0:Main@52] - JVM is shutting down.

**Comment by luisgmsft** [comment]
@rdearm1 what was the error you got while running Deploy.ps1? Was the Sample Environment setup or the docker vm set deploy (both files are equally named. Sorry about that).

Please let me know if you get the chance.

**Comment by jocontr** [comment]
Closing due to no repro.
