### ISSUE TITLE
clientMonitor container can't resolve zookeepers' name

### ISSUE THREAD

**Issue by marcelo-salvatori** [mspnp/ha-nva#46]
Hello,

When I complete the lab, it seems like my clientMonitor won't comunicate with zookeper because it can't resolve the name.

I get the following error:

`2018-08-02 13:29:36,957 INFO  [main:ZooKeeper@438] - Initiating client connection, connectString=zookeeper1:2181,zookeeper2:2182,zookeeper3:2183 sessionTimeout=60000 watcher=org.apache.curator.ConnectionState@52aa2946
2018-08-02 13:29:36,961 ERROR [main:CuratorFrameworkImpl@566] - Background exception was not retry-able or retry gave up
java.net.UnknownHostException: zookeeper1: Name does not resolve
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
        at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
        at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
        at java.net.InetAddress.getAllByName(InetAddress.java:1192)
        at java.net.InetAddress.getAllByName(InetAddress.java:1126)
        at org.apache.zookeeper.client.StaticHostProvider.<init>(StaticHostProvider.java:61)
        at org.apache.zookeeper.ZooKeeper.<init>(ZooKeeper.java:445)
        at org.apache.curator.utils.DefaultZookeeperFactory.newZooKeeper(DefaultZookeeperFactory.java:29)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl$2.newZooKeeper(CuratorFrameworkImpl.java:150)
        at org.apache.curator.HandleHolder$1.getZooKeeper(HandleHolder.java:94)
        at org.apache.curator.HandleHolder.getZooKeeper(HandleHolder.java:55)
        at org.apache.curator.ConnectionState.reset(ConnectionState.java:218)
        at org.apache.curator.ConnectionState.start(ConnectionState.java:103)
        at org.apache.curator.CuratorZookeeperClient.start(CuratorZookeeperClient.java:190)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.start(CuratorFrameworkImpl.java:259)
        at com.microsoft.azure.practices.nvadaemon.NvaDaemon.createClient(NvaDaemon.java:50)
        at com.microsoft.azure.practices.nvadaemon.NvaDaemon.start(NvaDaemon.java:70)
        at com.microsoft.azure.practices.nvadaemon.Main.runDaemon(Main.java:24)
        at com.microsoft.azure.practices.nvadaemon.Main.main(Main.java:78)
2018-08-02 13:29:36,968 DEBUG [main:NvaDaemon@51] - Waiting for Zookeeper connection
`

I don't know if it has anything to do with the fact that tey are getting the same IP

`msroot@docker2:~$ sudo docker exec -it clientMonitor2 ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP qlen 1000
    link/ether 00:0d:3a:4d:f0:86 brd ff:ff:ff:ff:ff:ff
    inet 10.0.0.103/27 brd 10.0.0.127 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::20d:3aff:fe4d:f086/64 scope link
       valid_lft forever preferred_lft forever
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN
    link/ether 02:42:6e:c8:83:68 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:6eff:fec8:8368/64 scope link
       valid_lft forever preferred_lft forever`

**Comment by luisgmsft** [comment]
@marcelo-salvatori, by strictly following the doc, looks like zookeeper1, zookeeper2 and zookeeper 3 (line 3 in the[ linked file for download & edit](https://raw.githubusercontent.com/mspnp/ha-nva/master/ha-nva-deployment/scripts/nvadaemon-remote.json)) must be renamed to docker1, docker2 and docker3 correspondingly as suggested in this picture (https://github.com/mspnp/ha-nva/blob/master/media/json-connectionstring.png).


Please let me know if this helps!

**Comment by hallihan** [comment]
Looking through old issues, it appears that the suggestion from Aug 30, 2018 should address this.
